### ISSUE TITLE
issue with object "Validation"

### ISSUE THREAD

**Issue by vontomar** [nialov/fractopo#3] opened 2022-03-25 16:52 UTC
Hi Nikolas,

I wrote you a mail earlier today asking about the state of your tool. I downloaded your package to try it out.
In the "trace validation" section of the documentation there is the object "Validation" which I cannot import.

I get the error message:
ImportError: cannot import name 'Validation' from 'fractopo' (unknown location)

Have you renamed or changed this object in the meantime?

Thanks a lot in advance and best wishes,
Martin

**Comment by nialov** [comment] 2022-03-25 19:16
Hey,

Firstly, thanks for trying out the tool! Now to your issue. I believe you might have an error in your package installation as

~~~python
from fractopo import Validation
~~~

is a valid import. You can try importing straight from the file where the `Validation` object is defined as so:

~~~python
from fractopo.tval.trace_validation import Validation
~~~

If the errors persists, could you describe how you have installed the tool? With `conda` or `pip` and on what platform (Windows, Linux, MacOS)? Does `import fractopo` work?

Also the notebooks in the documentation are probably the best "tutorials" for using my tool in Python (which you might have already found):

- https://fractopo.readthedocs.io/en/latest/notebooks/fractopo_validation_1.html
- https://fractopo.readthedocs.io/en/latest/notebooks/fractopo_validation_2.html

**Comment by nialov** [comment] 2022-03-25 19:21
Also: I believe I have not received your email. If you sent it to my work email: nikolas.ovaskainen@gtk.fi it might have been flagged by the over-zealous spam filter. I'm also reachable at nikolasovaskainen@gmail.com

**Comment by vontomar** [comment] 2022-03-25 19:57
Hi Nikolas,

Thanks for your reply. Now, the error does not show up any more but I have the following error message:

runfile('D:/education/Python/master project/MA_fractopo_outcrop_analysis_001.py', wdir='D:/education/Python/master project')
Traceback (most recent call last):
  File D:\education\Python\master project\MA_fractopo_outcrop_analysis_001.py:4 in <module>
    import pandas as pd
  File ~\AppData\Roaming\Python\Python39\site-packages\pandas\__init__.py:22 in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File ~\AppData\Roaming\Python\Python39\site-packages\pandas\compat\__init__.py:14 in <module>
    from pandas._typing import F
  File ~\AppData\Roaming\Python\Python39\site-packages\pandas\_typing.py:78 in <module>
    ArrayLike = Union["ExtensionArray", np.ndarray]
AttributeError: module 'numpy' has no attribute 'ndarray'

I installed fractopo inside Anaconda using Spyder. I am trying to find the error now. Thanks a lot for your help!

Best wishes,
Martin

PS: The mail I sent to nikolas.a.ovaskainen@utu.fi.

**Comment by vontomar** [comment] 2022-03-25 20:01
Here I am also sending you my script:
[MA_fractopo_outcrop_analysis_001.zip](https://github.com/nialov/fractopo/files/8353514/MA_fractopo_outcrop_analysis_001.zip)

**Comment by vontomar** [comment] 2022-03-25 20:12
I tried the following:
1 - pip uninstall -y numpy
2 - pip uninstall -y setuptools
3 - pip install setuptools
4 - pip install numpy

no success

**Comment by vontomar** [comment] 2022-03-25 20:13
Perhaps it might be due to the last two lines here:

Installing collected packages: setuptools
Successfully installed setuptools-61.0.0
Note: you may need to restart the kernel to use updated packages.
WARNING: Error parsing requirements for numpy: [Errno 2] No such file or directory: 'c:\\users\\martin_vontobel\\.conda\\envs\\fractopo-env\\lib\\site-packages\\numpy-1.22.3.dist-info\\METADATA'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, which is not installed.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.

**Comment by vontomar** [comment] 2022-03-26 01:16
Hi again,

I re-installed Anaconda and I am back to the

"ImportError: cannot import name 'Validation' from 'fractopo' (unknown location)"

messge from above.
This just to answer your question how I installed fractopo. It was via the conda command
"conda install -c conda-forge fractopo".

Thanks for your advice regarding the tutorials. I will have a look at them. Do you perhaps know why I get the above error message?

If I use the alternative command you suggested above, I get the following message:
ModuleNotFoundError: No module named 'fractopo.tval.trace_validation'

The "import fractopo" worked find.

Many thanks for your help in advance and kind regards,
Martin

**Comment by nialov** [comment] 2022-03-26 08:57
Try the following in the Anaconda prompt:

~~~bash
# Create new environment just for the fractopo package
# fractopo-env is just the name for the environment, you can choose any name
conda env create -n fractopo-env
# Activate that environment
conda activate fractopo-env
# Install fractopo
conda install -c conda-forge fractopo
# Open python prompt within that environment
python
~~~

You should end up in a python shell where `fractopo` should be installed. Now try

~~~python
from fractopo import Validation
~~~

I do my own `fractopo` development and use in a Linux environment where I can use `pip` to install the package. I'll test things in `conda` on monday if this doesn't work!

**Comment by vontomar** [comment] 2022-03-26 10:41
Hi Nikolas,

Thanks again for your help. The above steps are exactly the ones I followed. I opened the navigator, selected "Environments" to the left of the window, clicked "create", entered the name, clicked again onto "create". Now I can see the environment in the dropdown menu of the navigator. I select it, then click "launch" to launch Spyder.

This might seem a bit basic a question, but in QGIS where I prepare my lineament study with NetworkGT, I have difficulties snapping nodes to lines. Do you perhaps know how to proceed properly? I know there is a function"snap points to lines" but it doesn't show and I can't find it via the plugins installer.

Your help is much appreciated, have a good weekend!

Martin

**Comment by vontomar** [comment] 2022-03-26 10:56
Ok, I figured out how to use the snapping tool via View/Toolsbars/Snapping Toolbars :)

**Comment by nialov** [comment] 2022-03-29 06:23
Sorry, I could not reproduce your issue. `conda` installation can be finicky and found another installation bug while testing:

~~~
OSError: could not find or load spatialindex_c-64.dll
~~~

That one is related to `rtree` installation. Fixed it with the following commands within the environment:

~~~bash
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda update python
~~~

You could try the same although the error is different. Beyond that I believe your error is specific to your installation. Have you tried with another IDE other than spyder, such as visual studio code? You can launch it from within the activated environment prompt with `code .` and choose the python interpreter in visual studio code. Or have you tested the imports in just the python prompt (launched with `python` command)?

**Comment by vontomar** [comment] 2022-04-24 09:22
Hello NikolasSorry for the late reply and many thanks for getting in touch. I haven't tried another IDE but in the meantime I managed to write my own Python script for the analysis of fracture trace length data.I would have liked to use your package but this also helped me to improve my python skills.Many thanks and kind regards from Switzerland,MartinNikolas Ovaskainen ***@***.***> schrieb am 29. März 2022 um 8:23:Sorry, I could not reproduce your issue. conda installation can be finicky and found another installation bug while testing:OSError: could not find or load spatialindex_c-64.dll
That one is related to rtree installation. Fixed it with the following commands within the environment:conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda update pythonYou could try the same although the error is different. Beyond that I believe your error is specific to your installation. Have you tried with another IDE other than spyder, such as visual studio code? You can launch it from within the activated environment prompt with code . and choose the python interpreter in visual studio code. Or have you tested the imports in just the python prompt (launched with python command)?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by nialov** [comment] 2023-04-27 07:00
I will close this issue at it no longer seems relevant.

**Closed by nialov** 2023-04-27 07:00 UTC
